In [2]:
from functools import partial
from typing import Iterable, Tuple, Union

import torch
import torch.nn.functional as F
from torch import Tensor, nn
from torch.fft import irfftn, rfftn


In [29]:
t = torch.randn(3,2,1)
t.shape

torch.Size([3, 2, 1])

In [27]:
torch.movedim(t, 1, 0).shape


torch.Size([2, 3, 1])

In [19]:
torch.movedim(t, 1, 0)

tensor([[[ 0.8270],
         [-1.7391],
         [-0.1026]],

        [[-0.1783],
         [-1.2065],
         [-0.8503]]])

In [30]:

torch.movedim(t, (1, 2), (0, 1)).shape
torch.movedim(t, (1, 2), (0, 1))

tensor([[[-0.8215, -0.0706,  1.0115]],

        [[ 0.4544, -0.5332, -0.0921]]])

In [54]:
x = torch.tensor([1, 2, 3, 4])
print(x.shape)
torch.unsqueeze(x, 0)

torch.Size([4])


tensor([[1, 2, 3, 4]])

In [58]:

x.unsqueeze(-2)


tensor([[1, 2, 3, 4]])

In [67]:
a = torch.randint(1,6, (1,3))
print(a)

tensor([[4, 5, 5]])


In [64]:
b = torch.randint(1,6, (3,1))
print(a)

tensor([[2, 3, 3]])


In [69]:
print(a)
print(b)
print(a @ b)

tensor([[4, 5, 5]])
tensor([[5],
        [1],
        [5]])
tensor([[50]])


In [4]:
mat1 = torch.eye(2)
print(mat1)
mat2 = torch.ones(2, 2)
print(mat2)
print(torch.kron(mat1, mat2))

tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [0., 0., 1., 1.],
        [0., 0., 1., 1.]])


In [9]:
t4d = torch.randint(2,6, (3,3,4,2))
p1d = (1, 1) # pad last dim by 1 on each side
print(t4d)

tensor([[[[3, 4],
          [3, 4],
          [2, 4],
          [2, 4]],

         [[3, 4],
          [5, 2],
          [3, 4],
          [2, 4]],

         [[5, 2],
          [3, 4],
          [4, 5],
          [2, 2]]],


        [[[4, 2],
          [4, 3],
          [5, 3],
          [3, 5]],

         [[4, 4],
          [5, 3],
          [2, 5],
          [3, 2]],

         [[2, 4],
          [4, 5],
          [4, 2],
          [3, 3]]],


        [[[3, 2],
          [3, 2],
          [4, 3],
          [2, 4]],

         [[3, 5],
          [2, 5],
          [5, 5],
          [5, 5]],

         [[4, 5],
          [3, 4],
          [5, 5],
          [2, 3]]]])


In [10]:

out = F.pad(t4d, p1d, "constant", 0)  # effectively zero padding
print(out.size())
print(out)


torch.Size([3, 3, 4, 4])
tensor([[[[0, 3, 4, 0],
          [0, 3, 4, 0],
          [0, 2, 4, 0],
          [0, 2, 4, 0]],

         [[0, 3, 4, 0],
          [0, 5, 2, 0],
          [0, 3, 4, 0],
          [0, 2, 4, 0]],

         [[0, 5, 2, 0],
          [0, 3, 4, 0],
          [0, 4, 5, 0],
          [0, 2, 2, 0]]],


        [[[0, 4, 2, 0],
          [0, 4, 3, 0],
          [0, 5, 3, 0],
          [0, 3, 5, 0]],

         [[0, 4, 4, 0],
          [0, 5, 3, 0],
          [0, 2, 5, 0],
          [0, 3, 2, 0]],

         [[0, 2, 4, 0],
          [0, 4, 5, 0],
          [0, 4, 2, 0],
          [0, 3, 3, 0]]],


        [[[0, 3, 2, 0],
          [0, 3, 2, 0],
          [0, 4, 3, 0],
          [0, 2, 4, 0]],

         [[0, 3, 5, 0],
          [0, 2, 5, 0],
          [0, 5, 5, 0],
          [0, 5, 5, 0]],

         [[0, 4, 5, 0],
          [0, 3, 4, 0],
          [0, 5, 5, 0],
          [0, 2, 3, 0]]]])


In [29]:
print(t4d.size())
p2d = (2, 1, 1, 1, 1, 1) # pad last dim by (1, 1) and 2nd to last by (2, 2)
out = F.pad(t4d, p2d, "constant", 0)
print(out.size())
print(out)

torch.Size([3, 3, 4, 2])
torch.Size([3, 5, 6, 5])
tensor([[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]],

         [[0, 0, 0, 0, 0],
          [0, 0, 3, 4, 0],
          [0, 0, 3, 4, 0],
          [0, 0, 2, 4, 0],
          [0, 0, 2, 4, 0],
          [0, 0, 0, 0, 0]],

         [[0, 0, 0, 0, 0],
          [0, 0, 3, 4, 0],
          [0, 0, 5, 2, 0],
          [0, 0, 3, 4, 0],
          [0, 0, 2, 4, 0],
          [0, 0, 0, 0, 0]],

         [[0, 0, 0, 0, 0],
          [0, 0, 5, 2, 0],
          [0, 0, 3, 4, 0],
          [0, 0, 4, 5, 0],
          [0, 0, 2, 2, 0],
          [0, 0, 0, 0, 0]],

         [[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 

In [35]:
source = torch.randint(2,6, (10,11,12,13))
pad1 = (1, 2,3,4) # pad last dim by 1 on each side
print(source.size())
print(source.size(-1))
output = F.pad(source, pad1, "constant", 0)  # effectively zero padding
print(output.size())
# print(output)
print(source.size())
pad2 = (2, 1, 1, 1, 1, 1) # pad last dim by (1, 1) and 2nd to last by (2, 2)
output = F.pad(source, pad2, "constant", 0)
print(output.size())
# print(output)

torch.Size([10, 11, 12, 13])
13
torch.Size([10, 11, 19, 16])
torch.Size([10, 11, 12, 13])
torch.Size([10, 13, 14, 16])


In [38]:
print(source.size(-2))

12
